apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/media
images:
  - name: threshold/media
    newName: core.harbor.domain/threshold/media
    digest: sha256:9f2ee825566aa83b0ce4e07e892d2e4c721fa876dc89509e8aa6379b53bb3e91
patches:
  - target:
      kind: ConfigMap
      name: media-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
