apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/media
images:
  - name: threshold/media
    newName: core.harbor.domain/threshold/media
    digest: sha256:f5f2494a70e4f2b062076be4bddbab4d47a6ef4803816ae5e33bc7c8b63ce73d
patches:
  - target:
      kind: ConfigMap
      name: media-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
