apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/media
images:
  - name: threshold/media
    newName: core.harbor.domain/threshold/media
    digest: sha256:fedc18c426e0f1aab9534a2f4196ef80c0f9b11111372bc98b017635da5b27be
patches:
  - target:
      kind: ConfigMap
      name: media-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
