apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: users-email
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/part-of: threshold
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: users-email
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: THRESHOLD_SMTP_ENABLED
      remoteRef:
        key: threshold/users/email
        property: THRESHOLD_SMTP_ENABLED
    - secretKey: THRESHOLD_SMTP_USERNAME
      remoteRef:
        key: threshold/users/email
        property: THRESHOLD_SMTP_USERNAME
    - secretKey: THRESHOLD_SMTP_PASSWORD
      remoteRef:
        key: threshold/users/email
        property: THRESHOLD_SMTP_PASSWORD
    - secretKey: THRESHOLD_SMTP_FROM
      remoteRef:
        key: threshold/users/email
        property: THRESHOLD_SMTP_FROM
    - secretKey: THRESHOLD_WEB_HOST
      remoteRef:
        key: threshold/users/email
        property: THRESHOLD_WEB_HOST
