apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/auth-gateway
  - ingress.yaml
images:
  - name: threshold/auth-gateway
    newName: core.harbor.domain/threshold/auth-gateway
    digest: sha256:e59d7bec1e8f3544ffda5867cfaf8b5a764466b29addce935ccca176c37e4187
patches:
  - target:
      kind: ConfigMap
      name: auth-gateway-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
