apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/users
images:
  - name: threshold/users
    newName: core.harbor.domain/threshold/users
    digest: sha256:a8b22a4fd7e0bf3b8636c57611c21b70575bc22a6067f552a94558c1befe830c
patches:
  - target:
      kind: ConfigMap
      name: users-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
