apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/users
images:
  - name: threshold/users
    newName: core.harbor.domain/threshold/users
    digest: sha256:2f8df36e8aeebff46d6e75bf7c520744f3f6e81b2827e113c7a23bd688310335
patches:
  - target:
      kind: ConfigMap
      name: users-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
