apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/users
images:
  - name: threshold/users
    newName: core.harbor.domain/threshold/users
    digest: sha256:260c75dafb9ff1721ebb9335de300ceb820cb3a21f3f165af85d77794a53b053
patches:
  - target:
      kind: ConfigMap
      name: users-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
