apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/events
images:
  - name: threshold/events
    newName: core.harbor.domain/threshold/events
    digest: sha256:9277241a5a2321a513db18e3ec20c882d311cbefe371853db07fe7400fd03231
patches:
  - target:
      kind: ConfigMap
      name: events-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
