apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/events
images:
  - name: threshold/events
    newName: core.harbor.domain/threshold/events
    digest: sha256:9362757e249883e920c123e4099bd3bd8c326f55e5daf5e4224269e94635c080
patches:
  - target:
      kind: ConfigMap
      name: events-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
