apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: woodpecker-webhook
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: woodpecker-webhook
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflared
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudflared
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: server
              app.kubernetes.io/instance: woodpecker
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: woodpecker-server-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: woodpecker
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: woodpecker-webhook
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: woodpecker-webhook-poller
      ports:
        - protocol: TCP
          port: 8000
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: agent
              app.kubernetes.io/instance: woodpecker
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: woodpecker-release-agent
      ports:
        - protocol: TCP
          port: 9000
