apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/web
  - certificate.yaml
  - ingress.yaml
patches:
  - path: auth-cookie-secure-patch.yaml
images:
  - name: threshold/web
    newName: core.harbor.domain/threshold/web
    digest: sha256:98e425f4e55d01bb9a89c18ca7be4eab816d0e2845da5ad22a9c78d2fcf7af4f
