apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/web
  - certificate.yaml
  - ingress.yaml
patches:
  - path: auth-cookie-secure-patch.yaml
images:
  - name: threshold/web
    newName: core.harbor.domain/threshold/web
    digest: sha256:6daa607b0c2781c2d589ec429f85b1ffe2737d16e49e142b1e66ecaa98a80e32
