apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/web
  - certificate.yaml
  - ingress.yaml
patches:
  - path: auth-cookie-secure-patch.yaml
images:
  - name: threshold/web
    newName: core.harbor.domain/threshold/web
    digest: sha256:ebb1ddc12316f9519a375abcf6b5e9fa27aae354f7c095dbfbe44b960e25a2af
