apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threshold-cloudflared
  namespace: argocd
  labels:
    app.kubernetes.io/name: threshold-cloudflared
    app.kubernetes.io/part-of: threshold
    app.kubernetes.io/component: tunnel
spec:
  project: platform
  source:
    repoURL: https://github.com/fbialogrecki/threshold.git
    targetRevision: main
    path: infra/kustomize/base/platform/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
