apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threshold-security
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: threshold
spec:
  project: security
  source:
    repoURL: https://github.com/fbialogrecki/threshold.git
    targetRevision: main
    path: infra/kustomize/base/security
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
