apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/social
images:
  - name: threshold/social
    newName: core.harbor.domain/threshold/social
    digest: sha256:ba6dfb63ee1ee882452f97a3564de1ebdb8ab99949ba1463fc5e7ecf59d65af4
patches:
  - target:
      kind: ConfigMap
      name: social-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
