apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/social
images:
  - name: threshold/social
    newName: core.harbor.domain/threshold/social
    digest: sha256:6c9593408ee1a4551b8850be4dc808467693bd1fe191275481bb2dbe2d610ceb
patches:
  - target:
      kind: ConfigMap
      name: social-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
