apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threshold
resources:
  - ../../../base/social
images:
  - name: threshold/social
    newName: core.harbor.domain/threshold/social
    digest: sha256:c5f8f9e3b661b3d8add547f0a95e6bdbedbff6b533e133decdd0475607690607
patches:
  - target:
      kind: ConfigMap
      name: social-config
    patch: |-
      - op: replace
        path: /data/THRESHOLD_ENVIRONMENT
        value: local
