apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- networkpolicies.yaml
- certificates.yaml
- https-redirects.yaml
- adguard-ingress.yaml
- web-ip-redirect.yaml
- notifications-rbac.yaml
- workload-hardening.yaml
