apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false,DisableClientSideApplyMigration=true,Prune=false
spec:
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: server
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
          hostPort: 0
